name: Build Plugin

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Initialize modding environment
        uses: beat-forge/init-beatsaber@v1
        with:
          token: ${{ github.token }}
          repo: beat-forge/beatsaber-stripped

      - name: Download Mod Dependencies
        uses: Goobwabber/download-beatmods-deps@1.3
        with:
          manifest: ${{ github.workspace }}/KeyRemapper/KeyRemapper/manifest.json

      - name: Build
        id: Build
        run: dotnet build --configuration Release
        env:
          BeatSaberDir: ${{ github.workspace }}/Refs/

      - name: Echo Filename
        run: echo $BUILDTEXT \($ASSEMBLYNAME\)
        env:
          BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
          ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.Build.outputs.filename }}
          path: ${{ steps.Build.outputs.artifactpath }}
